# This file was generated by GoReleaser. DO NOT EDIT.
cask "trvl" do
  version "1.10.0"

  on_macos do
    on_intel do
      sha256 "e53bd3cbec0b8385742d8fc8d21df74fb1ea6a1674814f72fda4cc2835922cfe"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7188a0474227ca246d50b4aaec707733dcb43c89669bef7f01944526fa9e3786"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0542ea95e9acb786fcc9fde7020ab6d814e94fb5d0e0007335d1b8ea891e4146"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f4bde42d619d5f64fa48c8777e35dc4829249fa925941974221436ec23d34b37"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "trvl"
  desc "AI travel agent: flights, hotels and transport via MCP, no API keys"
  homepage "https://github.com/MikkoParkkola/trvl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trvl"

  # No zap stanza required

  caveats <<~EOS
    Run `trvl mcp install` to connect trvl to Claude Desktop, Cursor,
    Windsurf, Codex, VS Code Copilot, Zed, or another MCP client.
  EOS
end
