# This file was generated by GoReleaser. DO NOT EDIT.
cask "trvl" do
  version "1.11.0"

  on_macos do
    on_intel do
      sha256 "2c4cfc394e8af7a57a2f9a929716f5b7fc89edd390967576541d83806f72ebda"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "be9c1a6146f93031077298fcacc2329bfba9d9ca046782926f63ad9fc1a615ca"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c2cc7f3144ea86ebb4f30aaabacbd2b60df9e75e5ddf2c6be0d4b6aaf8e5c798"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "df5b59d4a08dd8b6f180834e286264e3ed4f78c8d48f9a0a84e4e4eb23d88658"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "trvl"
  desc "AI travel agent: flights, hotels and transport via MCP, no API keys"
  homepage "https://github.com/MikkoParkkola/trvl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trvl"

  # No zap stanza required

  caveats <<~EOS
    Run `trvl mcp install` to connect trvl to Claude Desktop, Cursor,
    Windsurf, Codex, VS Code Copilot, Zed, or another MCP client.
  EOS
end
