# This file was generated by GoReleaser. DO NOT EDIT.
cask "trvl" do
  version "1.9.2"

  on_macos do
    on_intel do
      sha256 "9682b26a86305969933b30e2abd66de3e77e732255ddc7470ced674a44b4ef7f"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "89c93a500cfb8d210d3dfe981e2ff6a2bee0beedede800fbe8156345b5a5c0de"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ee49d149ee09bf6e3606a269da560d92e3088b71c96aec1c7ee107faa0326a41"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6fceeb0e0ef50d5eb63344eb707e1b490cdaff361c03f466b78a9eb329056e5b"
      url "https://github.com/MikkoParkkola/trvl/releases/download/v#{version}/trvl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "trvl"
  desc "AI travel agent: flights, hotels and transport via MCP, no API keys"
  homepage "https://github.com/MikkoParkkola/trvl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trvl"

  # No zap stanza required

  caveats <<~EOS
    Run `trvl mcp install` to connect trvl to Claude Desktop, Cursor,
    Windsurf, Codex, VS Code Copilot, Zed, or another MCP client.
  EOS
end
