# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trvl < Formula
  desc "Google Flights + Hotels from your terminal — MCP server, 32 tools, no API keys"
  homepage "https://github.com/MikkoParkkola/trvl"
  version "0.3.13"
  license "PolyForm-Noncommercial-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MikkoParkkola/trvl/releases/download/v0.3.13/trvl_0.3.13_darwin_amd64.tar.gz"
      sha256 "01e0c520cb33deb72c18f7f685645ef3db2244d18ec388dd05af135ebdff4cb6"

      define_method(:install) do
        bin.install "trvl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MikkoParkkola/trvl/releases/download/v0.3.13/trvl_0.3.13_darwin_arm64.tar.gz"
      sha256 "9d887d7b3cc3fa61bf92482199ce6b89a507216b6148f6cc317d6ae7e1cda497"

      define_method(:install) do
        bin.install "trvl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MikkoParkkola/trvl/releases/download/v0.3.13/trvl_0.3.13_linux_amd64.tar.gz"
      sha256 "f9c9974c0005e863f2416cbf0820e133e0da580064e53e1f02ed53a56e0814d6"
      define_method(:install) do
        bin.install "trvl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MikkoParkkola/trvl/releases/download/v0.3.13/trvl_0.3.13_linux_arm64.tar.gz"
      sha256 "132653e2ecae8020716b26d1aa31a64059a7c8338176c08203343d165db4a7f4"
      define_method(:install) do
        bin.install "trvl"
      end
    end
  end

  test do
    system "#{bin}/trvl", "version"
  end
end
