# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trvl < Formula
  desc "Google Flights + Hotels from your terminal — MCP server, 41 tools, no API keys"
  homepage "https://github.com/MikkoParkkola/trvl"
  version "0.9.0"
  license "PolyForm-Noncommercial-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MikkoParkkola/trvl/releases/download/v0.9.0/trvl_0.9.0_darwin_amd64.tar.gz"
      sha256 "5f7d36725b19450eac99fe886fc3224b9099b7a83eae6054ceb6618b529ba987"

      define_method(:install) do
        bin.install "trvl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MikkoParkkola/trvl/releases/download/v0.9.0/trvl_0.9.0_darwin_arm64.tar.gz"
      sha256 "4504b677c5c1a733f25f04bcf2a43e4991956160456dc9a1cfb676ccd32da610"

      define_method(:install) do
        bin.install "trvl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MikkoParkkola/trvl/releases/download/v0.9.0/trvl_0.9.0_linux_amd64.tar.gz"
      sha256 "8608c8408dd70758f7734a6d34af06c93dbee218c65cf3ccd7eb461d4edaeec1"
      define_method(:install) do
        bin.install "trvl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MikkoParkkola/trvl/releases/download/v0.9.0/trvl_0.9.0_linux_arm64.tar.gz"
      sha256 "c46b8c14d67ebdae2899bf15ad9819cee367c6aea5f2a8b0bdd19208a3658156"
      define_method(:install) do
        bin.install "trvl"
      end
    end
  end

  test do
    system "#{bin}/trvl", "version"
  end
end
